Models/Cidade.cs
using System.Collections.Generic;

namespace ProjetoCidades.Models
{
    public class Cidade
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Estado { get; set; }
        public int Habitantes { get; set; }

       
    }
}

Models/ErrorViewModel.cs
using System;

namespace ProjetoCidades.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CidadesController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using ProjetoCidades.Models;
using ProjetoCidades.Repositorio;

namespace ProjetoCidades.Controllers
{
    public class CidadesController: Controller
    {
        Cidade cidade = new Cidade();
        CidadeRep objCidadeRep = new CidadeRep();
        public IActionResult Index(){
            var lista = objCidadeRep.Listar();
            //não vou usar uma viewbag como usamos no projeto anterior

            return View(lista);
        }
        public IActionResult CidadesEstados(){
            //vai lá dentro da View procurar esse arquivo CidaedesEstados
            var lista = objCidadeRep.Listar();
            return View(lista);
        }
        public IActionResult TodosOsDados(){
            var lista = objCidadeRep.Listar();
            return View(lista);
        }

        [HttpGet]
        public IActionResult Cadastrar(){
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar([Bind]Cidade cidade){
            objCidadeRep.Cadastrar(cidade);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Editar(int id){
            var lista = objCidadeRep.Listar().Where(x => x.Id == id).FirstOrDefault();
            return View(lista);

        }

        [HttpPost]
        public IActionResult Editar([Bind]Cidade cidade){
            objCidadeRep.Editar(cidade);
            return RedirectToAction("Index");
        }

        
        public IActionResult Excluir(int id){
            var lista = objCidadeRep.Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

Views/Cidades/Cadastrar.cshtml
@model ProjetoCidades.Models.Cidade
<div>
<h2>Cadastrar</h2>
<h4>Cidade</h4>
<hr>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Cadastrar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form=group"´>
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control"/>
                <span asp-validation-for="Nome" class="text-danger"></span>                
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control"/>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Habitantes" class="control-label"></label>
                <input asp-for="Habitantes" class="form-control"/>
                <span asp-validation-for="Habitantes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-default"/>
            </div>
        </form>
</div>

</div>

Views/Cidades/CidadesEstados.cshtml
@model IEnumerable<ProjetoCidades.Models.Cidade>
<div>
    <h2>Cidades da Gabriela Topzera</h2>
    <hr>
    @{
        foreach(var item in Model){
            <li>@item.Nome - @item.Estado</li>
        }
    }
</div>




    

Views/Cidades/Editar.cshtml
@model ProjetoCidades.Models.Cidade
<div>
<h2>Editar</h2>
<h4>Cidade</h4>
<hr>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form=group"´>
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" disabled="disabled/>
                <span asp-validation-for="Id" class="text-danger"></span>                
            </div>
            
            <div class="form=group"´>
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control"/>
                <span asp-validation-for="Nome" class="text-danger"></span>                
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control"/>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Habitantes" class="control-label"></label>
                <input asp-for="Habitantes" class="form-control"/>
                <span asp-validation-for="Habitantes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-default"/>
            </div>
        </form>
</div>

</div>

Views/Cidades/Excluir.cshtml
@model ProjetoCidades.Models.Cidade
<div>
<h2>Excluir</h2>
<h4>Cidade</h4>
<hr>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Excluir">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form=group"´>
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" disabled="disabled/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            
            <div class="form=group"´>
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control"/>
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control"/>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Habitantes" class="control-label"></label>
                <input asp-for="Habitantes" class="form-control"/>
                <span asp-validation-for="Habitantes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Excluir" class="btn btn-default"/>
            </div>
        </form>
</div>

</div>

Views/Cidades/Index.cshtml
@model IEnumerable<ProjetoCidades.Models.Cidade>
<div>
    <!--djfjaskldjflkj-->
    <h2>Cidades Gabriela Topzera ☻♥</h2>

    <p>
            <a asp-action="Cadastrar">Cadastrar nova cidade</a>
    </p>

    <table class="table"> 
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Estado</th>
                <th>Habitantes</th>
                <th></th>
            </tr>
        </thead>
        <tbody>         
            @{
            foreach(var item in Model){
                <tr>
                 <td>@item.Id</td>
                    <td>@item.Nome</td>
                    <td>@item.Estado</td>
                    <td>@item.Habitantes</td>
                    <td>
                        <a asp-action="Editar" asp-route-id="@item.Id">Editar</a>
                        <a asp-action="Detalhes" asp-route-id="@item.Id">Detalhes</a>
                        <a asp-action="Excluir" asp-route-id="@item.Id">Excluir</a>
                    </td>
                </tr>            
        }
    }
        </tbody>
    </table>
    
</div>

Views/Cidades/TodosOsDados.cshtml
<div>
    
    <h2>Todos os Dados do Martché</h2>
    <table>
        <tr>
            <th>Id</th> <!--table HEADER-->
            <th>Nome</th>
            <th>Estado</th>
            <th>Habitantes</th>
        </tr>
        @{
            foreach(var item in Model){
                <tr>
                    <td>@item.Id</td> //table DATA
                    <td>@item.Nome</td>
                    <td>@item.Estado</td>
                    <td>@item.Habitantes</td>
                </tr>
            }
        }
    </table>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoCidades</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Cidades" asp-action="Index" class="navbar-brand">ProjetoCidades</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Cidades" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Cidades" asp-action="CidadesEstados">Cidades e Estados</a></li>
                    <li><a asp-area="" asp-controller="Cidades" asp-action="TodosOsDados">Todos os Dados</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ProjetoCidades</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>